### ISSUE TITLE
Empty Dialogs

### ISSUE THREAD

**Issue by walterpalladino** [jsanchezv/JSpeccy#16]
I compiled the app using JDK 16. I'm running the app on Windows and the dialogs are empty.
I check on internet and could be problems with JOptionPane which is not thread safe.
Any thoughts?
Regards.
Walter--

**Comment by jsanchezv** [comment]
I compile JSpeccy with JDK 11 and runs the emulator with Java 17 without any problem. I don't have any Windows to test, and my last test on Windows was using XP, long time ago.

Can you try with the latest JDK 17.0.1 LTS?

I can put a jar on my DropBox if you need it.

**Comment by walterpalladino** [comment]
I will try compiling it with JDK 17 but if you can share your build to test it on Windows will be greate.
Thank you in advance.
Walter--

**Comment by jsanchezv** [comment]
https://www.dropbox.com/s/l9imcrgejwahrpu/JSpeccy.jar?dl=0

**Comment by walterpalladino** [comment]
I really appreciate your time.
I found I was always testing with opengl and there is when the dialogs are empty.
Using the xrender option false dialogs are shown properly.
Thank you.
Walter--

**Comment by walterpalladino** [comment]
I really appreciate your time.
I found I was always testing with opengl and there is when the dialogs are empty.
Using the xrender option false dialogs are shown properly.
Thank you.
Walter--
