### ISSUE TITLE
JSpeccy v1.0.2: "Java Exception has occurred"

### ISSUE THREAD

**Issue by Korb** [jsanchezv/JSpeccy#32]
When running jspeccy.jar, a notification appears:

> Java Virtual Machine Launcher
> Java Exception has occurred.
> OK

The application does not start.

Java 8 Update 431 (64-bit) 8.0.4310.10 (**October 15, 2024**)
Microsoft Windows 10.0.19045.5198

**Comment by neirons** [comment]
It works perfectly for me.

java 21.0.5 2024-10-15 LTS
Java SE Runtime Environment (build 21.0.5+9-LTS-239)
Microsoft Windows 11 Pro 10.0.26100 Build 26100

**Comment by doraemoncito** [comment]
> When running jspeccy.jar, a notification appears:
> 
> > Java Virtual Machine Launcher
> > Java Exception has occurred.
> > OK
> 
> The application does not start.
> 
> Java 8 Update 431 (64-bit) 8.0.4310.10 (October 15, 2024) Microsoft Windows 10.0.19045.5198

You need Java 21 to run JSpeccy

**Comment by Korb** [comment]
> [Java **8** Update 431 (64-bit) 8.0.4310.10 (**October 15, 2024**)](https://www.java.com/download/ie_manual.jsp)

> You need Java **21** to run JSpeccy

That is, to run this application, the latest version of Java for Windows for end users is not enough, but you need to additionally install the Java Development Kit from OTN downloads or Oracle OpenJDK downloads from jdk.java.net? Was this really necessary?

**Comment by jsanchezv** [comment]
No, you don't need JDK, only JRE, but upgrade to a LTS is mandatory.

Many Java libraries needs Java 11 at least, and SpringBoot 3.4 needs Java 17. So, the most reasonable option is Java 21.
