### ISSUE TITLE
Bug in MemIoOps

### ISSUE THREAD

**Issue by jawhiting** [jsanchezv/JSpeccy#6]
In z80core/memIoOps, your setPorts method sets the ram member variable instead of the ports.
(sorry, I meant MemIoOps. Line 43).

**Comment by jsanchezv** [comment]
I cant't understand what's the problem. Anyway, the MemIoOps default implementacion isn't used in JSpeccy.

**Comment by jawhiting** [comment]
Sorry I mean line 43 should be:
z80ports = ports;

I don’t know anything about the codebase, was just browsing and noticed it.

**Comment by jsanchezv** [comment]
Yes, it's true, thanks by your bug report.

I've corrected another two off-by-one bugs in constructor with param.

Best regards
