### ISSUE TITLE
Nombre de la variable que almacena el número de lineas en la parte superior de la pantalla

### ISSUE THREAD

**Issue by doraemoncito** [jsanchezv/JSpeccy#8]
https://github.com/jsanchezv/JSpeccy/blob/6420c4f73ba6b24d16ca7fba9079094b00cd8d2b/src/machine/MachineTypes.java#L27

Creo que esta variable probablemente se debería llamar `upBorderHeight` ya que almacena el número de lineas, no el número de columnas.

**Comment by jsanchezv** [comment]
Esta issue se resolvió desde tu propio commit.
